// Builds ~/Applications/Outreach.app and puts it in the Dock.
// The app runs the code straight from this folder, so `git pull` updates it with no rebuild.
// Rebuild only if this folder moves or the Electron version in package.json changes.
//   node scripts/make-app.js
const fs = require('fs')
const os = require('os')
const path = require('path')
const { execFileSync } = require('child_process')

const REPO = path.resolve(__dirname, '..')
const SOURCE = path.join(REPO, 'node_modules', 'electron', 'dist', 'Electron.app')
const APPS = path.join(os.homedir(), 'Applications')
const DEST = path.join(APPS, 'Outreach.app')
const PLIST = path.join(DEST, 'Contents', 'Info.plist')
const RESOURCES = path.join(DEST, 'Contents', 'Resources')

function run(command, args, options = {}) {
  return execFileSync(command, args, { stdio: ['ignore', 'pipe', 'pipe'], ...options }).toString()
}

// The app icon, already on the standard macOS grid (1024 canvas, 824 px tile, rounded, soft shadow)
// so it sits at the same size as every other app in the Dock.
const ICON = path.join(REPO, 'assets', 'icon.png')

async function makeIcon() {
  const sharp = require(path.join(REPO, 'node_modules', 'sharp'))
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'outreach-icon-'))
  const iconset = path.join(work, 'outreach.iconset')
  fs.mkdirSync(iconset)
  for (const size of [16, 32, 64, 128, 256, 512, 1024]) {
    const png = await sharp(ICON).resize(size, size).png().toBuffer()
    if (size <= 512) fs.writeFileSync(path.join(iconset, `icon_${size}x${size}.png`), png)
    if (size >= 32) fs.writeFileSync(path.join(iconset, `icon_${size / 2}x${size / 2}@2x.png`), png)
  }
  run('iconutil', ['-c', 'icns', iconset, '-o', path.join(RESOURCES, 'outreach.icns')])
  fs.rmSync(work, { recursive: true, force: true })
}

function setPlist(key, value) {
  run('plutil', ['-replace', key, '-string', value, PLIST])
}

function addToDock() {
  const current = run('defaults', ['read', 'com.apple.dock', 'persistent-apps'])
  if (current.includes(DEST)) return false
  const entry = `<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>file://${encodeURI(DEST)}/</string><key>_CFURLStringType</key><integer>15</integer></dict></dict></dict>`
  run('defaults', ['write', 'com.apple.dock', 'persistent-apps', '-array-add', entry])
  run('killall', ['Dock'])
  return true
}

async function main() {
  if (!fs.existsSync(SOURCE)) throw new Error('Run npm install first (Electron is missing).')
  fs.mkdirSync(APPS, { recursive: true })
  fs.rmSync(DEST, { recursive: true, force: true })
  run('ditto', [SOURCE, DEST])

  // Shown as Outreach (Dock, Finder, menu bar), with its own icon and identity.
  setPlist('CFBundleName', 'Outreach')
  setPlist('CFBundleDisplayName', 'Outreach')
  setPlist('CFBundleIdentifier', 'com.nutricode.outreach')
  setPlist('CFBundleIconFile', 'outreach.icns')
  await makeIcon()

  // The app's code is this repo.
  const appDir = path.join(RESOURCES, 'app')
  fs.mkdirSync(appDir, { recursive: true })
  fs.writeFileSync(path.join(appDir, 'package.json'), JSON.stringify({ main: 'main.js', private: true }, null, 2))
  fs.writeFileSync(path.join(appDir, 'main.js'), `// Generated by scripts/make-app.js: runs Outreach from the repo, so git pull updates the app.
const path = require('path')
const { app } = require('electron')
const REPO = ${JSON.stringify(REPO)}
// Same internal name and data folder as when started from Start Review.command, so the Instagram
// login and everything else stored by the app carries over.
app.setName('Electron')
app.setPath('userData', path.join(app.getPath('appData'), 'Electron'))
process.chdir(REPO)
require(path.join(REPO, 'app-main.js'))
`)

  run('codesign', ['--force', '--deep', '--sign', '-', DEST])
  run('touch', [DEST])
  const added = addToDock()
  console.log(`Built ${DEST}${added ? ' and added it to the Dock' : ' (already in the Dock)'}.`)
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
